apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    repoURL: https://github.com/org0031-landing-zone/argocd-platform-setup.git
    path: <TO_OVERLAY>
    targetRevision: main
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.14-3.0/#removing-default-ignores-of-preserveunknownfields-for-crd
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/preserveUnknownFields
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - PruneLast=true
