apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: argocd-prd-store
    kind: SecretStore
  target:
    name: <TO_OVERLAY>
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
      data:
        name: <TO_OVERLAY>
        server: "{{ .serverUrl }}"
        config: |
          {
            "execProviderConfig": {
              "command": "argocd-k8s-auth",
              "env": {
                "AZURE_CLIENT_ID": "<ARGOCD_SERVER/APP-CONTROLLER_SA_UMI>",
                "AZURE_TENANT_ID": "<YOUR_TENANT_ID>",
                "AZURE_FEDERATED_TOKEN_FILE": "/var/run/secrets/azure/tokens/azure-identity-token",
                "AZURE_AUTHORITY_HOST": "https://login.microsoftonline.com/",
                "AAD_ENVIRONMENT_NAME": "AzurePublicCloud",
                "AAD_LOGIN_METHOD": "workloadidentity"
              },
              "args": ["azure"],
              "apiVersion": "client.authentication.k8s.io/v1beta1"
            },
            "tlsClientConfig": {
              "insecure": false,
              "caData": "{{ .caCert }}"
            }
          }
  data:
  - secretKey: caCert
    remoteRef:
      key: <TO_OVERLAY>
  - secretKey: serverUrl
    remoteRef:
      key: <TO_OVERLAY>
