apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - ingress.yaml
  - argocdapp.yaml
  - argocd-server-rbac-clusterrolebinding.yaml
  - argocd-server-rbac-clusterrole.yaml