apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../base/aks-clusters

patches:
- target:
    name: cluster-external-secret
    kind: ExternalSecret
  patch: |-
    - op: replace
      path: /metadata/name
      value: aks-int-we-cluster-external-secret
    - op: replace
      path: /spec/target/name
      value: aks-int-we-cluster-secret
    - op: replace
      path: /spec/target/template/data/name
      value: aks-int-we
    - op: replace
      path: /spec/data/0/remoteRef/key
      value: secret/aks-int-we-ca-cert
    - op: replace
      path: /spec/data/1/remoteRef/key
      value: secret/aks-int-we-server-url