# reference: https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-repo-creds-yaml
# TODO: Generalise this to support a base config
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: github-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: https://github.com/<YOUR-ORGANIZATION>
        githubAppID: "{{ .app_id }}"
        githubAppInstallationID: "{{ .installation_id }}"
        githubAppPrivateKey: "{{ .private_key_pem }}"
  data:
    - secretKey: app_id
      remoteRef: { key: eks-restricted/github, property: app_id }
    - secretKey: installation_id
      remoteRef: { key: eks-restricted/github, property: installation_id }
    - secretKey: private_key_pem
      remoteRef: { key: eks-restricted/github/private-key }