apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- ../../base
- https://raw.githubusercontent.com/argoproj/argo-cd/v3.1.6/manifests/ha/install.yaml
- projects

configMapGenerator:
- name: argocd-cm
  behavior: merge
  files:
  - oidc.config=config/oidc.yaml
  envs:
  - config/argocd-cm.env

- name: argocd-cmd-params-cm
  behavior: merge
  envs:
  - config/argocd-cmd-params-cm.env

# Reference: https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-rbac-cm-yaml/
- name: argocd-rbac-cm
  behavior: merge
  files:
  - config/policy.csv
  envs:
  - config/rbac.env

patches:
- path: patches.yaml

# - path: azure-patch.yaml # (uncomment if using Azure Workload Identity)

- target:
    kind: ClusterRole
    name: argocd-server
  patch: |-
    - op: add
      path: /rules/-
      value:
        apiGroups: [""]
        resources: ["pods/exec"]
        verbs: ["create"]
