apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: argocd-prd-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://<argocd-prd-akv>.vault.azure.net"
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
  conditions:
  - namespaces: [ argocd, platform, app-prd ]
