apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster-secret-store.yaml
- namespace.yaml

namespace: external-secrets

helmCharts:
- version: 0.18.2
  releaseName: external-secrets
  name: external-secrets
  namespace: external-secrets
  repo: https://charts.external-secrets.io
  valuesInline:
    serviceAccount:
      annotations:
      name: external-secrets